### ISSUE TITLE
Supported Databases

### ISSUE THREAD

**Issue by pythoneer** [tvallotton/sqlx-models#20]
What databases are currently supported? I was about to play around with it and was wondering if it currently is even possible to create migrations other than sqlite that are supported by sqlx right now. I see some occurrences of postgresql in the code and dialect sections but i don't really now how to navigate the code yet to answer that myself. It is unfortunately not mentioned in the readme etc. but some places in the code made it look like it can determine the database from the connection string `DATABASE_URL=sqlite://` ... `DATABASE_URL=postgres://` but it looks like it is only generating sqlite compatible migrations atm.

**Comment by tvallotton** [comment]
Sorry for not answering right away, as I'm not at home right now. The generation for Postgres is about the same. However, the example may not be working for Postgres as I believe that User is a reserved keyword in that SQL dialect, try naming the table Users or Profile. The generation for SQLite should be fully compatible with Postgres aside for those minor exceptions related to reserved keywords.

Other than that, it is completely fine to change the database url. You can also specify a different directory with the `--source` option. Also, I wouldn't recommend deleting migrations if you don't intend to drop the database, it's better to revert them.

**Comment by pythoneer** [comment]
> Sorry for not answering right away, I'm not at home right now.

No worries, you're exceptionally responsive! Its working flawless now. I just didn't gave much thought about it myself as i am not writing DDL that often – should have spotted it myself. I just thought there is something wrong with the process i am doing and "expected" the example to just work without modifications. 

Its a very nice project!
