### ISSUE TITLE
Postgresql serial type

### ISSUE THREAD

**Issue by pythoneer** [tvallotton/sqlx-models#22]
in postgresql there is a handy [`serial` type](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-SERIAL) would be very convenient to mark some fields (e.g. id) to have this type instead of the regular `i32` -> `integer` conversion or in general more power to choose types. Is there any other way to have auto inc ids?

**Comment by tvallotton** [comment]
Not yet but I'm working on it currently. For the next version it will be available.

**Comment by tvallotton** [comment]
@pythoneer You now can use `models::Serial`.

**Comment by mikemoore13** [comment]
Now what about big serial
